### ISSUE TITLE
I don't know how to configure parameters

### ISSUE THREAD

**Issue by sweetquiet** [GMahmoud/virtual_costmap_layer#1]
Hello, how do you configure parameters in the common costmap.yaml file, or can you write a tutorial, thank you

**Comment by GMahmoud** [comment]
Hello @sweetquiet, 

Sorry, I did not see your issue :/. I haven't been working on this repo for a long time. However, I put it a new version lately with a sample folder. I hope that's clear for you. 
Soon I will continue on improving the README to make the plugin better 

Cheers

**Comment by sweetquiet** [comment]
@GMahmoud Hi,wow,  Glad to hear from you! I'll keep watching. Cheers
